### ISSUE TITLE
Add subgraph

### ISSUE THREAD

**Issue by julienbrg** [w3hc/gov-ui#76]
https://github.com/w3hc/gov-subgraph

**Comment by bertux** [comment]
Build completed: QmQ8dJap9ZuXUuj9ZvesxbVHfkUcBZuTrztD7bBvQhBunC

Deployed to https://thegraph.com/studio/subgraph/gov-subgraph

Subgraph endpoints:
Queries (HTTP):     https://api.studio.thegraph.com/query/52496/gov-subgraph/v0.0.1

**Comment by bertux** [comment]
documented at https://docs.chainstack.com/docs/subgraphs-tutorial-fetching-subgraph-data-using-javascript#using-the-urql-library

**Comment by bertux** [comment]
DEVELOPMENT QUERY URL - LATEST VERSION :
https://api.studio.thegraph.com/query/52496/gov-subgraph/version/latest

```
query proposalsCreated {
  proposalCreateds {
    proposalId
    blockNumber
    calldatas
    description
    voteEnd
    voteStart
    transactionHash
  }
}
```

**Comment by bertux** [comment]
subgraph query example at https://github.com/bertux/subgraph-query/blob/main/index.ts

**Comment by bertux** [comment]
Query whith chronological ordering:
{
  proposalCreateds(orderDirection: desc, orderBy: voteEnd) {
    proposalId
    blockNumber
    calldatas
    description
    voteEnd
    voteStart
    transactionHash
  }
}
